package frc.robot.subsystems.climber;

public enum ClimberState {
 IDLE,
 DEEP_CLIMB_DEPLOY,
 DEEP_CLIMB_UNLATCH,
 DEEP_CLIMB_RETRACT,
 DEEP_CLIMB_UNWIND,
 MANUAL_DEEP_CLIMB_RETRACT,
 MANUAL_DEEP_CLIMB_UNWIND,
 DEEP_CLIMB_WAIT
}
