package frc.robot.stateMachine;

public enum RobotState {
  PREPARE_IDLE,
  IDLE,
  PREPARE_L1_ROW_1,
  WAIT_L1_ROW_1,
  SCORE_L1_ROW_1,
  PREPARE_L1_ROW_2,
  WAIT_L1_ROW_2,
  SCORE_L1_ROW_2,
  PREPARE_INTAKE,
  INTAKE,
  PREPARE_CORAL_STATION_INTAKE,
  CORAL_STATION_INTAKE
}
