package frc.robot.stateMachine;

import edu.wpi.first.wpilibj.util.Color;

public enum RobotState {
  PREPARE_IDLE,
  IDLE,
  PREPARE_L1_ROW_1,
  WAIT_L1_ROW_1,
  SCORE_L1_ROW_1,
  PREPARE_L1_ROW_2,
  WAIT_L1_ROW_2,
  SCORE_L1_ROW_2,
  PREPARE_INTAKE,
  INTAKE,
  PREPARE_CORAL_STATION_INTAKE,
  CORAL_STATION_INTAKE,
  DEEP_CLIMB_DEPLOY,
  DEEP_CLIMB_CLIMB,
  DEEP_CLIMB_UNCLIMB,
  DEEP_CLIMB_WAIT,
  PREPARE_DEEP_CLIMB,
  MANUAL_CLIMB_FORWARD,
  MANUAL_CLIMB_BACKWARD

}
